# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
    # Only build on successful pushes to master or next.
    push:
        branches: [master, next]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [12.x]

        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
                  registry-url: "https://npm.pkg.github.com/"
                  scope: "@bdsanfelippo"
            # Skip post-install scripts here, as a malicious
            # script could steal NODE_AUTH_TOKEN.
            - run: npm ci --ignore-scripts
            - run: npm run lint
            - run: npm test
            - run: npm run build
            - run: npm run pack-prod
            - run: npx semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  # reset the NODE_AUTH_TOKEN for the package publishing
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  CI: true
